/*
 * Blocking issue #17 gate.
 *
 * The JSON corpus is deliberately loaded as data, never generated by this
 * script.  Every assertion below compares an oracle result with literal
 * committed expectations.  Pass a different path as the first argument (or
 * DRDICE_GOLDEN_FILE) to audit a proposed corpus change; a disagreement must
 * fail the process.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  MAX_ATTEMPTS,
  MAX_BOUND,
  SCHEMA_VERSION,
  SEQUENCE_PROFILE,
  oracleInitialize,
  oracleNext,
  oracleRestoreReplay,
  oracleRestoreState,
  oracleSerializeState,
  oracleSample,
  oracleStateFromWords,
} from "./oracle.mjs";

const directory = path.dirname(fileURLToPath(import.meta.url));
const defaultGoldenFile = path.join(directory, "golden-vectors.json");
const goldenFile = process.env.DRDICE_GOLDEN_FILE ?? process.argv[2] ?? defaultGoldenFile;

/* These are independent review anchors, not values read from the oracle or
 * corpus.  A coordinated change to both files must fail until the profile is
 * deliberately re-reviewed. */
const PINNED_SCHEMA_VERSION = 1;
const PINNED_SEQUENCE_PROFILE = "xoshiro128ss-1.1/warmup16-msb-chunk-rejection-2";
const PINNED_MAX_BOUND = 100;
const PINNED_MAX_ATTEMPTS = 5;
const PINNED_CANONICAL_SEED = ["00000001", "00000002", "00000003", "00000004"];
const PINNED_CANONICAL_RAW_WORDS = [
  "e2c8791a",
  "891246f3",
  "d4df5524",
  "b08ff665",
  "925a6b9c",
  "836c24aa",
  "cfe4f018",
  "ff234fba",
  "2027d8ca",
  "5ffd9895",
];
const PINNED_CANONICAL_SUCCESSOR_STATES = [
  ["dcd45053", "a4b0c23c", "1026cbfd", "4248c1a7"],
  ["3a2c53c8", "68425992", "ad76e3ae", "c01cdf37"],
  ["9272d56d", "ff18e9f4", "13e99466", "f4352d42"],
];
const PINNED_CRAFTED_REJECTION_STATE = ["b0e8eac3", "f2d79146", "a51937ed", "21243868"];
const PINNED_CRAFTED_EXHAUSTION_STATE = ["8615d1a1", "16f6c103", "cbc1fbff", "055c3220"];

const fail = (message) => {
  throw new Error(`[issue-17] ${message}`);
};

const assert = (condition, message) => {
  if (!condition) fail(message);
};

const json = (value) => JSON.stringify(value);

const equal = (actual, expected, label) => {
  if (json(actual) !== json(expected)) {
    fail(`${label}\n  actual:   ${json(actual)}\n  expected: ${json(expected)}`);
  }
};

const readGolden = () => {
  let parsed;
  try {
    parsed = JSON.parse(fs.readFileSync(goldenFile, "utf8"));
  } catch (error) {
    fail(`cannot read or parse golden corpus ${goldenFile}: ${error.message}`);
  }
  return parsed;
};

const words = (value, label) => {
  assert(Array.isArray(value) && value.length === 4, `${label} must contain exactly four words`);
  for (const [index, word] of value.entries()) {
    assert(typeof word === "string" && /^[0-9a-f]{8}$/.test(word), `${label}[${index}] is not a canonical lowercase Word32`);
  }
  return value;
};

const projectResult = (result) => {
  if (result.ok) {
    return {
      ok: true,
      value: result.value.value,
      attempts: result.value.attempts,
      state: [...result.value.state.words],
    };
  }
  if (result.code === "sampling-attempts-exhausted") {
    return {
      ok: false,
      code: result.code,
      details: {
        maximumAttempts: result.details.maximumAttempts,
        attempts: result.details.attempts,
        state: [...result.details.state.words],
      },
    };
  }
  return result;
};

const widthForBound = (bound) => {
  let width = 0;
  let range = 1;
  while (range < bound) {
    range *= 2;
    width += 1;
  }
  return width;
};

const checkTransitionCorpus = (golden) => {
  const vector = golden.rawWordVector;
  assert(vector && typeof vector === "object", "raw-word vector is missing");
  words(golden.canonicalSeed, "canonicalSeed");
  equal(golden.canonicalSeed, PINNED_CANONICAL_SEED, "canonical Seed changed without a reviewed profile change");
  equal(vector.seed, PINNED_CANONICAL_SEED, "raw-word seed must use the established human-seed vector");
  assert(Array.isArray(vector.words) && vector.words.length >= 10, "at least ten literal raw words are required");
  assert(Array.isArray(vector.nextStates) && vector.nextStates.length >= 3, "at least three literal Next Generator States are required");
  assert(Array.isArray(vector.transitions) && vector.transitions.length >= 10, "at least ten literal transition records are required");

  equal(
    vector.words.slice(0, PINNED_CANONICAL_RAW_WORDS.length),
    PINNED_CANONICAL_RAW_WORDS,
    "canonical raw words changed without a reviewed profile change",
  );
  equal(
    vector.nextStates.slice(0, PINNED_CANONICAL_SUCCESSOR_STATES.length),
    PINNED_CANONICAL_SUCCESSOR_STATES,
    "canonical Next Generator States changed without a reviewed profile change",
  );

  for (const [index, word] of vector.words.entries()) {
    assert(typeof word === "string" && /^[0-9a-f]{8}$/.test(word), `raw word ${index} is not a canonical lowercase Word32`);
  }
  for (const [index, state] of vector.nextStates.entries()) words(state, `nextStates[${index}]`);

  const initialized = oracleInitialize(vector.seed);
  assert(initialized.ok, `canonical Seed unexpectedly rejected: ${json(initialized)}`);
  let current = initialized.value;

  for (const [position, transition] of vector.transitions.entries()) {
    assert(transition.index === position, `transition index ${position} is not stable`);
    words(transition.inputState, `transitions[${position}].inputState`);
    words(transition.nextState, `transitions[${position}].nextState`);
    equal(current.words, transition.inputState, `transition ${position} input state disagrees with its predecessor`);
    const actual = oracleNext(current);
    assert(actual.ok, `transition ${position} unexpectedly failed: ${json(actual)}`);
    equal(actual.value.word, transition.word, `transition ${position} word disagrees with committed golden data`);
    equal(actual.value.state.words, transition.nextState, `transition ${position} Next Generator State disagrees with committed golden data`);
    current = actual.value.state;
  }

  equal(vector.words, vector.transitions.slice(0, vector.words.length).map(({ word }) => word), "raw word projection disagrees with transition records");
  equal(vector.nextStates, vector.transitions.slice(0, vector.nextStates.length).map(({ nextState }) => nextState), "successor-state projection disagrees with transition records");
};

const checkAttemptPath = (vector) => {
  words(vector.inputState, `${vector.id}.inputState`);
  assert(Number.isInteger(vector.bound) && vector.bound >= 1 && vector.bound <= MAX_BOUND, `${vector.id} has an unsupported bound`);
  assert(Number.isInteger(vector.maximumAttempts) && vector.maximumAttempts >= 0 && vector.maximumAttempts <= MAX_ATTEMPTS, `${vector.id} has unsupported attempt fuel`);
  assert(Array.isArray(vector.attemptWords), `${vector.id}.attemptWords is missing`);
  assert(Array.isArray(vector.candidateChunks), `${vector.id}.candidateChunks is missing`);
  assert(Array.isArray(vector.attemptStates), `${vector.id}.attemptStates is missing`);
  equal(vector.attemptWords.length, vector.candidateChunks.length, `${vector.id} candidate-chunk count does not match attempt words`);
  equal(vector.attemptWords.length, vector.attemptStates.length, `${vector.id} attempt-state count does not match attempt words`);
  assert(vector.attemptWords.length <= vector.maximumAttempts, `${vector.id} consumes more attempts than its fuel`);
  const width = widthForBound(vector.bound);
  let current = oracleStateFromWords(vector.inputState);
  let stopped = false;
  for (let attempt = 0; attempt < vector.attemptWords.length; attempt += 1) {
    const step = oracleNext(current);
    assert(step.ok, `${vector.id} attempt ${attempt} unexpectedly failed`);
    const value = Number.parseInt(step.value.word, 16) >>> 0;
    const candidates = [];
    if (width === 0) candidates.push(0);
    for (let offset = 0; width > 0 && offset + width <= 32; offset += width) {
      candidates.push((value >>> (32 - offset - width)) & ((2 ** width) - 1));
    }
    const acceptedAt = candidates.findIndex((candidate) => candidate < vector.bound);
    const inspected = acceptedAt < 0 ? candidates : candidates.slice(0, acceptedAt + 1);
    equal(step.value.word, vector.attemptWords[attempt], `${vector.id} attempt ${attempt} word disagrees with oracle`);
    equal(inspected, vector.candidateChunks[attempt], `${vector.id} attempt ${attempt} candidate chunks disagree with oracle`);
    equal(step.value.state.words, vector.attemptStates[attempt], `${vector.id} attempt ${attempt} successor disagrees with oracle`);
    current = step.value.state;
    if (acceptedAt >= 0) {
      stopped = true;
      assert(attempt + 1 === vector.attemptWords.length, `${vector.id} records work after acceptance`);
      break;
    }
  }
  if (vector.attemptWords.length > 0 && !stopped) {
    assert(vector.attemptWords.length === vector.maximumAttempts, `${vector.id} exhausted before recording all fuel`);
  }
  if (vector.attemptWords.length === 0) equal(current.words, vector.inputState, `${vector.id} zero-fuel path advanced state`);

  words(vector.expected.ok ? vector.expected.state : vector.expected.details.state, `${vector.id}.expected state`);
  const actual = oracleSample(oracleStateFromWords(vector.inputState), vector.bound, vector.maximumAttempts);
  const expected = vector.expected.ok
    ? vector.expected
    : vector.expected;
  equal(projectResult(actual), expected, `${vector.id} oracle result disagrees with committed golden data`);
  if (actual.ok) {
    assert(actual.value.value >= 0 && actual.value.value < vector.bound, `${vector.id} accepted value is outside [0, bound)`);
    equal(actual.value.attempts, vector.attemptWords.length, `${vector.id} attempt count is not exact`);
  } else {
    assert(actual.code === "sampling-attempts-exhausted", `${vector.id} must use structured exhaustion for a failed sample`);
    equal(actual.details.attempts, vector.attemptWords.length, `${vector.id} exhausted attempt count is not exact`);
  }
};

const checkSamplingCorpus = (golden) => {
  assert(Array.isArray(golden.sampling) && golden.sampling.length > 0, "sampling corpus is missing");
  for (const vector of golden.sampling) checkAttemptPath(vector);

  const byId = new Map(golden.sampling.map((vector) => [vector.id, vector]));
  for (const id of [
    "bound-one-consumes-one",
    "bound-two",
    "bound-eight-power",
    "bound-sixteen-power",
    "bound-three-non-power",
    "bound-six-non-power",
    "bound-one-hundred",
    "forced-rejection-then-acceptance",
    "exact-exhaustion-0",
    "exact-exhaustion-1",
    "exact-exhaustion-2",
    "exact-exhaustion-3",
    "exact-exhaustion-4",
    "exact-exhaustion-5",
  ]) assert(byId.has(id), `required sampling vector ${id} is missing`);

  const forced = byId.get("forced-rejection-then-acceptance");
  equal(golden.craftedRejectionState, PINNED_CRAFTED_REJECTION_STATE, "crafted rejection state changed without a reviewed profile change");
  equal(forced.inputState, golden.craftedRejectionState, "forced-rejection vector must use craftedRejectionState exactly");
  assert(forced.bound === 7 && forced.maximumAttempts === 2, "forced-rejection vector must retain its bound-seven role");
  equal(forced.attemptWords, ["f244aa57"], "forced-rejection word changed without reviewed evidence");
  equal(forced.candidateChunks, [[7, 4]], "forced-rejection candidates must reject seven then accept four from one output");
  assert(forced.candidateChunks[0][0] >= forced.bound, "forced-rejection vector does not reject its first candidate");
  assert(forced.candidateChunks[0].at(-1) < forced.bound, "forced-rejection vector does not eventually accept");
  equal(golden.craftedExhaustionState, PINNED_CRAFTED_EXHAUSTION_STATE, "crafted exhaustion state changed without reviewed profile evidence");
  for (let fuel = 0; fuel <= PINNED_MAX_ATTEMPTS; fuel += 1) {
    const exhaustion = byId.get(`exact-exhaustion-${fuel}`);
    equal(exhaustion.inputState, golden.craftedExhaustionState, `exact-exhaustion-${fuel} must use craftedExhaustionState`);
    assert(exhaustion.expected.ok === false, `exact-exhaustion-${fuel} must fail`);
    assert(exhaustion.expected.code === "sampling-attempts-exhausted", `exact-exhaustion-${fuel} must report exhaustion`);
    assert(exhaustion.expected.details.maximumAttempts === fuel, `exact-exhaustion-${fuel} maximum is not literal fuel`);
    assert(exhaustion.expected.details.attempts === fuel, `exact-exhaustion-${fuel} consumed attempt count is not exact`);
  }
};

const checkReplayCorpus = (golden) => {
  const replay = golden.replay;
  assert(replay && typeof replay === "object", "replay corpus is missing");
  equal(replay.token.schemaVersion, SCHEMA_VERSION, "Replay Token schema version disagrees with oracle");
  equal(replay.token.sequenceProfile, SEQUENCE_PROFILE, "Replay Token profile disagrees with oracle");
  equal(replay.token.seed, golden.canonicalSeed, "Replay Token Seed is not canonical");
  const restored = oracleRestoreReplay(replay.token);
  assert(restored.ok, `valid Replay Token unexpectedly rejected: ${json(restored)}`);
  equal(restored.value.words, replay.restartState, "Replay Token did not restart from its Seed");
  const first = oracleNext(restored.value);
  assert(first.ok, "restarted Replay Token could not step");
  equal(first.value.word, replay.firstWord, "Replay Token first word disagrees with golden data");
  equal(first.value.state.words, replay.firstSuccessorState, "Replay Token first successor disagrees with golden data");

  const serialized = replay.serializedState;
  const serializedFromOracle = oracleSerializeState(first.value.state);
  assert(serializedFromOracle.ok, "a valid Generator State must serialize");
  equal(serializedFromOracle.value, serialized, "serialized-state golden data disagrees with oracle serialization");
  equal(serialized.schemaVersion, SCHEMA_VERSION, "Serialized Generator State schema version disagrees with oracle");
  equal(serialized.sequenceProfile, SEQUENCE_PROFILE, "Serialized Generator State profile disagrees with oracle");
  words(serialized.state, "serializedState.state");
  const resumed = oracleRestoreState(serialized);
  assert(resumed.ok, `valid serialized state unexpectedly rejected: ${json(resumed)}`);
  const next = oracleNext(resumed.value);
  assert(next.ok, "restored serialized state could not step");
  equal(next.value.word, replay.resumedWord, "Serialized Generator State did not resume at the next word");
  equal(next.value.state.words, replay.resumedSuccessorState, "Serialized Generator State successor disagrees with golden data");
  const serializedAgain = oracleSerializeState(resumed.value);
  assert(serializedAgain.ok, "a restored Generator State must serialize again");
  equal(serializedAgain.value, serialized, "serialize/restore round-trip changed the current Generator State");
};

const checkPinnedProfileAndInvalidPreflight = () => {
  assert(SCHEMA_VERSION === PINNED_SCHEMA_VERSION, "oracle schema version changed without a reviewed profile change");
  assert(SEQUENCE_PROFILE === PINNED_SEQUENCE_PROFILE, "oracle Sequence Profile changed without a reviewed profile change");
  assert(MAX_BOUND === PINNED_MAX_BOUND, "oracle maximum bound changed without a reviewed profile change");
  assert(MAX_ATTEMPTS === PINNED_MAX_ATTEMPTS, "oracle maximum attempts changed without a reviewed profile change");

  const initialized = oracleInitialize(PINNED_CANONICAL_SEED);
  assert(initialized.ok, "canonical Seed must initialize for invalid-preflight checks");
  const state = initialized.value;
  const before = [...state.words];

  const invalidBound = oracleSample(state, PINNED_MAX_BOUND + 1, 1);
  assert(!invalidBound.ok && invalidBound.code === "invalid-bound", "bound 101 must fail as invalid-bound");
  equal(invalidBound.details.bound, PINNED_MAX_BOUND + 1, "invalid bound diagnostic must retain 101");
  equal(state.words, before, "invalid bound 101 consumed Generator State");

  const invalidFuel = oracleSample(state, 1, PINNED_MAX_ATTEMPTS + 1);
  assert(!invalidFuel.ok && invalidFuel.code === "invalid-attempt-fuel", "fuel above the supported maximum must fail as invalid-attempt-fuel");
  equal(invalidFuel.details.maximumAttempts, PINNED_MAX_ATTEMPTS + 1, "invalid fuel diagnostic must retain its input");
  equal(state.words, before, "invalid fuel consumed Generator State");
};

const checkPrivateBoundary = () => {
  const oraclePath = path.join(directory, "oracle.mjs");
  const source = fs.readFileSync(oraclePath, "utf8");
  assert(!/\bimport\s+(?:[^"']+\s+from\s+)?["']/.test(source), "oracle must not import production or shared implementation modules");
  assert(!/(?:packages|src|dist)\//.test(source), "oracle must not reference package/source/dist implementation paths");
  assert(oraclePath.includes(`${path.sep}verification${path.sep}issue-17${path.sep}`), "oracle is outside the private verification boundary");
};

const checkNegativeBoundaryCases = () => {
  const malformedSeed = oracleInitialize(["0000000A", "00000000", "00000000", "00000001"]);
  assert(!malformedSeed.ok && malformedSeed.code === "invalid-seed-word", "oracle accepted a non-canonical Seed word");
  const nonStringSeedWords = ["00000001", 2, "00000000", "00000001"];
  const nonStringSeed = oracleInitialize(nonStringSeedWords);
  assert(!nonStringSeed.ok && nonStringSeed.code === "invalid-seed-word", "four-item non-string Seed was misclassified as a shape failure");
  equal(nonStringSeed.details.seed, nonStringSeedWords, "non-string Seed failure did not retain its input tuple");
  const malformedState = oracleNext(oracleStateFromWords(["0000000A", "00000000", "00000000", "00000001"]));
  assert(!malformedState.ok && malformedState.code === "invalid-state-word", "oracle accepted a non-canonical Generator State word");
  const nonStringStateWords = ["00000001", 2, "00000000", "00000001"];
  const nonStringState = oracleNext(oracleStateFromWords(nonStringStateWords));
  assert(!nonStringState.ok && nonStringState.code === "invalid-state-word", "four-item non-string Generator State was misclassified as a shape failure");
  equal(nonStringState.details.state, oracleStateFromWords(nonStringStateWords), "non-string Generator State failure did not retain its tagged state");
  const zeroSeed = oracleInitialize(["00000000", "00000000", "00000000", "00000000"]);
  assert(!zeroSeed.ok && zeroSeed.code === "invalid-seed-zero", "oracle accepted the all-zero Seed");
  const zeroState = oracleNext(oracleStateFromWords(["00000000", "00000000", "00000000", "00000000"]));
  assert(!zeroState.ok && zeroState.code === "invalid-state-zero", "oracle accepted the all-zero Generator State");
  const malformedReplay = oracleRestoreReplay({ schemaVersion: 1, sequenceProfile: SEQUENCE_PROFILE, seed: ["00000000"] });
  assert(!malformedReplay.ok && malformedReplay.code === "invalid-seed-shape", "Replay Token did not preserve Seed validation");
  const malformedSnapshot = oracleRestoreState({ schemaVersion: 1, sequenceProfile: SEQUENCE_PROFILE, state: ["0000000A", "00000000", "00000000", "00000001"] });
  assert(!malformedSnapshot.ok && malformedSnapshot.code === "invalid-state-word", "serialized state accepted a non-canonical word");
  equal(
    malformedSnapshot.details.state,
    oracleStateFromWords(["0000000A", "00000000", "00000000", "00000001"]),
    "serialized non-canonical-word failure did not normalize to a tagged Generator State",
  );
  const nonStringSnapshotWords = ["00000001", 2, "00000000", "00000001"];
  const nonStringSnapshot = oracleRestoreState({
    schemaVersion: 1,
    sequenceProfile: SEQUENCE_PROFILE,
    state: nonStringSnapshotWords,
  });
  assert(!nonStringSnapshot.ok && nonStringSnapshot.code === "invalid-state-word", "four-item non-string serialized state was misclassified as a shape failure");
  equal(
    nonStringSnapshot.details.state,
    oracleStateFromWords(nonStringSnapshotWords),
    "non-string serialized-state failure did not normalize to a tagged Generator State",
  );
  const zeroSnapshot = oracleRestoreState({
    schemaVersion: 1,
    sequenceProfile: SEQUENCE_PROFILE,
    state: ["00000000", "00000000", "00000000", "00000000"],
  });
  assert(!zeroSnapshot.ok && zeroSnapshot.code === "invalid-state-zero", "all-zero serialized state was not rejected");
  equal(
    zeroSnapshot.details.state,
    oracleStateFromWords(["00000000", "00000000", "00000000", "00000000"]),
    "all-zero serialized-state failure did not normalize to a tagged Generator State",
  );
  const malformedSnapshotShape = oracleRestoreState({ schemaVersion: 1, sequenceProfile: SEQUENCE_PROFILE, state: ["00000001"] });
  assert(!malformedSnapshotShape.ok && malformedSnapshotShape.code === "invalid-state-shape", "serialized state did not reject a short state structurally");
};

const main = () => {
  const golden = readGolden();
  checkPinnedProfileAndInvalidPreflight();
  assert(golden.schemaVersion === PINNED_SCHEMA_VERSION, "golden schema version changed without a reviewed profile change");
  assert(golden.sequenceProfile === PINNED_SEQUENCE_PROFILE, "golden Sequence Profile changed without a reviewed profile change");
  words(golden.canonicalSeed, "canonicalSeed");
  words(golden.craftedRejectionState, "craftedRejectionState");
  words(golden.craftedExhaustionState, "craftedExhaustionState");
  checkTransitionCorpus(golden);
  checkSamplingCorpus(golden);
  checkReplayCorpus(golden);
  checkNegativeBoundaryCases();
  checkPrivateBoundary();
  console.log(`[issue-17] oracle/golden checks passed (${path.relative(process.cwd(), goldenFile)})`);
};

try {
  main();
} catch (error) {
  console.error(error.message);
  process.exitCode = 1;
}
