/*
 * Blocking issue #17 gate.
 *
 * The JSON corpus is deliberately loaded as data, never generated by this
 * script.  Every assertion below compares an oracle result with literal
 * committed expectations.  Pass a different path as the first argument (or
 * DRDICE_GOLDEN_FILE) to audit a proposed corpus change; a disagreement must
 * fail the process.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  MAX_ATTEMPTS,
  MAX_BOUND,
  SCHEMA_VERSION,
  SEQUENCE_PROFILE,
  oracleInitialize,
  oracleNext,
  oracleRestoreReplay,
  oracleRestoreState,
  oracleSerializeState,
  oracleSample,
  oracleStateFromWords,
} from "./oracle.mjs";

const directory = path.dirname(fileURLToPath(import.meta.url));
const defaultGoldenFile = path.join(directory, "golden-vectors.json");
const goldenFile = process.env.DRDICE_GOLDEN_FILE ?? process.argv[2] ?? defaultGoldenFile;

/* These are independent review anchors, not values read from the oracle or
 * corpus.  A coordinated change to both files must fail until the profile is
 * deliberately re-reviewed. */
const PINNED_SCHEMA_VERSION = 1;
const PINNED_SEQUENCE_PROFILE = "xoshiro128ss-1.1/direct128-msb-rejection-1";
const PINNED_MAX_BOUND = 100;
const PINNED_MAX_ATTEMPTS = 4;
const PINNED_CANONICAL_SEED = ["00000001", "00000002", "00000003", "00000004"];
const PINNED_CANONICAL_RAW_WORDS = [
  "00002d00",
  "00000000",
  "005a7080",
  "04389d80",
  "79199d9b",
  "61963b24",
  "4cb9b57a",
  "de9d7431",
  "de458f35",
  "fdce1a54",
];
const PINNED_CANONICAL_SUCCESSOR_STATES = [
  ["00000007", "00000000", "00000402", "00003000"],
  ["00003007", "00000405", "00000405", "01800000"],
  ["01803402", "00003007", "00083e02", "0020280c"],
];
const PINNED_CRAFTED_REJECTION_STATE = ["b0e8eac3", "f2d79146", "a51937ed", "21243868"];

const fail = (message) => {
  throw new Error(`[issue-17] ${message}`);
};

const assert = (condition, message) => {
  if (!condition) fail(message);
};

const json = (value) => JSON.stringify(value);

const equal = (actual, expected, label) => {
  if (json(actual) !== json(expected)) {
    fail(`${label}\n  actual:   ${json(actual)}\n  expected: ${json(expected)}`);
  }
};

const readGolden = () => {
  let parsed;
  try {
    parsed = JSON.parse(fs.readFileSync(goldenFile, "utf8"));
  } catch (error) {
    fail(`cannot read or parse golden corpus ${goldenFile}: ${error.message}`);
  }
  return parsed;
};

const words = (value, label) => {
  assert(Array.isArray(value) && value.length === 4, `${label} must contain exactly four words`);
  for (const [index, word] of value.entries()) {
    assert(typeof word === "string" && /^[0-9a-f]{8}$/.test(word), `${label}[${index}] is not a canonical lowercase Word32`);
  }
  return value;
};

const projectResult = (result) => {
  if (result.ok) {
    return {
      ok: true,
      value: result.value.value,
      attempts: result.value.attempts,
      state: [...result.value.state.words],
    };
  }
  if (result.code === "sampling-attempts-exhausted") {
    return {
      ok: false,
      code: result.code,
      details: {
        maximumAttempts: result.details.maximumAttempts,
        attempts: result.details.attempts,
        state: [...result.details.state.words],
      },
    };
  }
  return result;
};

const widthForBound = (bound) => {
  let width = 0;
  let range = 1;
  while (range < bound) {
    range *= 2;
    width += 1;
  }
  return width;
};

const checkTransitionCorpus = (golden) => {
  const vector = golden.rawWordVector;
  assert(vector && typeof vector === "object", "raw-word vector is missing");
  words(golden.canonicalSeed, "canonicalSeed");
  equal(golden.canonicalSeed, PINNED_CANONICAL_SEED, "canonical Seed changed without a reviewed profile change");
  equal(vector.seed, PINNED_CANONICAL_SEED, "raw-word seed must use the established direct-Seed vector");
  assert(Array.isArray(vector.words) && vector.words.length >= 10, "at least ten literal raw words are required");
  assert(Array.isArray(vector.successorStates) && vector.successorStates.length >= 3, "at least three literal successor states are required");
  assert(Array.isArray(vector.transitions) && vector.transitions.length >= 10, "at least ten literal transition records are required");

  equal(
    vector.words.slice(0, PINNED_CANONICAL_RAW_WORDS.length),
    PINNED_CANONICAL_RAW_WORDS,
    "canonical raw words changed without a reviewed profile change",
  );
  equal(
    vector.successorStates.slice(0, PINNED_CANONICAL_SUCCESSOR_STATES.length),
    PINNED_CANONICAL_SUCCESSOR_STATES,
    "canonical successor states changed without a reviewed profile change",
  );

  for (const [index, word] of vector.words.entries()) {
    assert(typeof word === "string" && /^[0-9a-f]{8}$/.test(word), `raw word ${index} is not a canonical lowercase Word32`);
  }
  for (const [index, state] of vector.successorStates.entries()) words(state, `successorStates[${index}]`);

  const initialized = oracleInitialize(vector.seed);
  assert(initialized.ok, `canonical Seed unexpectedly rejected: ${json(initialized)}`);
  let current = initialized.value;

  for (const [position, transition] of vector.transitions.entries()) {
    assert(transition.index === position, `transition index ${position} is not stable`);
    words(transition.inputState, `transitions[${position}].inputState`);
    words(transition.successorState, `transitions[${position}].successorState`);
    equal(current.words, transition.inputState, `transition ${position} input state disagrees with its predecessor`);
    const actual = oracleNext(current);
    assert(actual.ok, `transition ${position} unexpectedly failed: ${json(actual)}`);
    equal(actual.value.word, transition.word, `transition ${position} word disagrees with committed golden data`);
    equal(actual.value.state.words, transition.successorState, `transition ${position} successor state disagrees with committed golden data`);
    current = actual.value.state;
  }

  equal(vector.words, vector.transitions.slice(0, vector.words.length).map(({ word }) => word), "raw word projection disagrees with transition records");
  equal(vector.successorStates, vector.transitions.slice(0, vector.successorStates.length).map(({ successorState }) => successorState), "successor-state projection disagrees with transition records");
};

const checkAttemptPath = (vector) => {
  words(vector.inputState, `${vector.id}.inputState`);
  assert(Number.isInteger(vector.bound) && vector.bound >= 1 && vector.bound <= MAX_BOUND, `${vector.id} has an unsupported bound`);
  assert(Number.isInteger(vector.maximumAttempts) && vector.maximumAttempts >= 0 && vector.maximumAttempts <= MAX_ATTEMPTS, `${vector.id} has unsupported attempt fuel`);
  assert(Array.isArray(vector.attemptWords), `${vector.id}.attemptWords is missing`);
  assert(Array.isArray(vector.candidates), `${vector.id}.candidates is missing`);
  assert(Array.isArray(vector.attemptStates), `${vector.id}.attemptStates is missing`);
  equal(vector.attemptWords.length, vector.candidates.length, `${vector.id} candidate count does not match attempt words`);
  equal(vector.attemptWords.length, vector.attemptStates.length, `${vector.id} attempt-state count does not match attempt words`);
  assert(vector.attemptWords.length <= vector.maximumAttempts, `${vector.id} consumes more attempts than its fuel`);
  const width = widthForBound(vector.bound);
  let current = oracleStateFromWords(vector.inputState);
  let stopped = false;
  for (let attempt = 0; attempt < vector.attemptWords.length; attempt += 1) {
    const step = oracleNext(current);
    assert(step.ok, `${vector.id} attempt ${attempt} unexpectedly failed`);
    const candidate = width === 0 ? 0 : Number.parseInt(step.value.word, 16) >>> (32 - width);
    equal(step.value.word, vector.attemptWords[attempt], `${vector.id} attempt ${attempt} word disagrees with oracle`);
    equal(candidate, vector.candidates[attempt], `${vector.id} attempt ${attempt} candidate disagrees with oracle`);
    equal(step.value.state.words, vector.attemptStates[attempt], `${vector.id} attempt ${attempt} successor disagrees with oracle`);
    current = step.value.state;
    if (candidate < vector.bound) {
      stopped = true;
      assert(attempt + 1 === vector.attemptWords.length, `${vector.id} records work after acceptance`);
      break;
    }
  }
  if (vector.attemptWords.length > 0 && !stopped) {
    assert(vector.attemptWords.length === vector.maximumAttempts, `${vector.id} exhausted before recording all fuel`);
  }
  if (vector.attemptWords.length === 0) equal(current.words, vector.inputState, `${vector.id} zero-fuel path advanced state`);

  words(vector.expected.ok ? vector.expected.state : vector.expected.details.state, `${vector.id}.expected state`);
  const actual = oracleSample(oracleStateFromWords(vector.inputState), vector.bound, vector.maximumAttempts);
  const expected = vector.expected.ok
    ? vector.expected
    : vector.expected;
  equal(projectResult(actual), expected, `${vector.id} oracle result disagrees with committed golden data`);
  if (actual.ok) {
    assert(actual.value.value >= 0 && actual.value.value < vector.bound, `${vector.id} accepted value is outside [0, bound)`);
    equal(actual.value.attempts, vector.attemptWords.length, `${vector.id} attempt count is not exact`);
  } else {
    assert(actual.code === "sampling-attempts-exhausted", `${vector.id} must use structured exhaustion for a failed sample`);
    equal(actual.details.attempts, vector.attemptWords.length, `${vector.id} exhausted attempt count is not exact`);
  }
};

const checkSamplingCorpus = (golden) => {
  assert(Array.isArray(golden.sampling) && golden.sampling.length > 0, "sampling corpus is missing");
  for (const vector of golden.sampling) checkAttemptPath(vector);

  const byId = new Map(golden.sampling.map((vector) => [vector.id, vector]));
  for (const id of [
    "bound-one-consumes-one",
    "bound-two",
    "bound-eight-power",
    "bound-sixteen-power",
    "bound-three-non-power",
    "bound-six-non-power",
    "bound-one-hundred",
    "forced-rejection-then-acceptance",
    "exact-exhaustion-0",
    "exact-exhaustion-1",
    "exact-exhaustion-2",
    "exact-exhaustion-3",
    "exact-exhaustion-4",
  ]) assert(byId.has(id), `required sampling vector ${id} is missing`);

  const forced = byId.get("forced-rejection-then-acceptance");
  equal(golden.craftedRejectionState, PINNED_CRAFTED_REJECTION_STATE, "crafted rejection state changed without a reviewed profile change");
  equal(forced.inputState, golden.craftedRejectionState, "forced-rejection vector must use craftedRejectionState exactly");
  assert(forced.bound === 7 && forced.maximumAttempts === 2, "forced-rejection vector must retain its two-attempt bound-seven role");
  equal(forced.attemptWords, ["f244aa57", "ddb72649"], "forced-rejection words changed without reviewed evidence");
  equal(forced.candidates, [7, 6], "forced-rejection candidates must reject seven then accept six");
  assert(forced.candidates[0] >= forced.bound, "forced-rejection vector does not reject its first candidate");
  assert(forced.candidates[forced.candidates.length - 1] < forced.bound, "forced-rejection vector does not eventually accept");
  for (let fuel = 0; fuel <= 4; fuel += 1) {
    const exhaustion = byId.get(`exact-exhaustion-${fuel}`);
    assert(exhaustion.expected.ok === false, `exact-exhaustion-${fuel} must fail`);
    assert(exhaustion.expected.code === "sampling-attempts-exhausted", `exact-exhaustion-${fuel} must report exhaustion`);
    assert(exhaustion.expected.details.maximumAttempts === fuel, `exact-exhaustion-${fuel} maximum is not literal fuel`);
    assert(exhaustion.expected.details.attempts === fuel, `exact-exhaustion-${fuel} consumed attempt count is not exact`);
  }
};

const checkReplayCorpus = (golden) => {
  const replay = golden.replay;
  assert(replay && typeof replay === "object", "replay corpus is missing");
  equal(replay.token.schemaVersion, SCHEMA_VERSION, "Replay Token schema version disagrees with oracle");
  equal(replay.token.sequenceProfile, SEQUENCE_PROFILE, "Replay Token profile disagrees with oracle");
  equal(replay.token.seed, golden.canonicalSeed, "Replay Token Seed is not canonical");
  const restored = oracleRestoreReplay(replay.token);
  assert(restored.ok, `valid Replay Token unexpectedly rejected: ${json(restored)}`);
  equal(restored.value.words, replay.restartState, "Replay Token did not restart from its Seed");
  const first = oracleNext(restored.value);
  assert(first.ok, "restarted Replay Token could not step");
  equal(first.value.word, replay.firstWord, "Replay Token first word disagrees with golden data");
  equal(first.value.state.words, replay.firstSuccessorState, "Replay Token first successor disagrees with golden data");

  const serialized = replay.serializedState;
  const serializedFromOracle = oracleSerializeState(first.value.state);
  assert(serializedFromOracle.ok, "a valid Generator State must serialize");
  equal(serializedFromOracle.value, serialized, "serialized-state golden data disagrees with oracle serialization");
  equal(serialized.schemaVersion, SCHEMA_VERSION, "Serialized Generator State schema version disagrees with oracle");
  equal(serialized.sequenceProfile, SEQUENCE_PROFILE, "Serialized Generator State profile disagrees with oracle");
  words(serialized.state, "serializedState.state");
  const resumed = oracleRestoreState(serialized);
  assert(resumed.ok, `valid serialized state unexpectedly rejected: ${json(resumed)}`);
  const next = oracleNext(resumed.value);
  assert(next.ok, "restored serialized state could not step");
  equal(next.value.word, replay.resumedWord, "Serialized Generator State did not resume at the next word");
  equal(next.value.state.words, replay.resumedSuccessorState, "Serialized Generator State successor disagrees with golden data");
  const serializedAgain = oracleSerializeState(resumed.value);
  assert(serializedAgain.ok, "a restored Generator State must serialize again");
  equal(serializedAgain.value, serialized, "serialize/restore round-trip changed the current Generator State");
};

const checkPinnedProfileAndInvalidPreflight = () => {
  assert(SCHEMA_VERSION === PINNED_SCHEMA_VERSION, "oracle schema version changed without a reviewed profile change");
  assert(SEQUENCE_PROFILE === PINNED_SEQUENCE_PROFILE, "oracle Sequence Profile changed without a reviewed profile change");
  assert(MAX_BOUND === PINNED_MAX_BOUND, "oracle maximum bound changed without a reviewed profile change");
  assert(MAX_ATTEMPTS === PINNED_MAX_ATTEMPTS, "oracle maximum attempts changed without a reviewed profile change");

  const initialized = oracleInitialize(PINNED_CANONICAL_SEED);
  assert(initialized.ok, "canonical Seed must initialize for invalid-preflight checks");
  const state = initialized.value;
  const before = [...state.words];

  const invalidBound = oracleSample(state, PINNED_MAX_BOUND + 1, 1);
  assert(!invalidBound.ok && invalidBound.code === "invalid-bound", "bound 101 must fail as invalid-bound");
  equal(invalidBound.details.bound, PINNED_MAX_BOUND + 1, "invalid bound diagnostic must retain 101");
  equal(state.words, before, "invalid bound 101 consumed Generator State");

  const invalidFuel = oracleSample(state, 1, PINNED_MAX_ATTEMPTS + 1);
  assert(!invalidFuel.ok && invalidFuel.code === "invalid-attempt-fuel", "fuel 5 must fail as invalid-attempt-fuel");
  equal(invalidFuel.details.maximumAttempts, PINNED_MAX_ATTEMPTS + 1, "invalid fuel diagnostic must retain 5");
  equal(state.words, before, "invalid fuel 5 consumed Generator State");
};

const checkPrivateBoundary = () => {
  const oraclePath = path.join(directory, "oracle.mjs");
  const source = fs.readFileSync(oraclePath, "utf8");
  assert(!/\bimport\s+(?:[^"']+\s+from\s+)?["']/.test(source), "oracle must not import production or shared implementation modules");
  assert(!/(?:packages|src|dist)\//.test(source), "oracle must not reference package/source/dist implementation paths");
  assert(oraclePath.includes(`${path.sep}verification${path.sep}issue-17${path.sep}`), "oracle is outside the private verification boundary");
};

const checkNegativeBoundaryCases = () => {
  const malformedSeed = oracleInitialize(["0000000A", "00000000", "00000000", "00000001"]);
  assert(!malformedSeed.ok && malformedSeed.code === "invalid-seed-word", "oracle accepted a non-canonical Seed word");
  const malformedState = oracleNext(oracleStateFromWords(["0000000A", "00000000", "00000000", "00000001"]));
  assert(!malformedState.ok && malformedState.code === "invalid-state-word", "oracle accepted a non-canonical Generator State word");
  const zeroSeed = oracleInitialize(["00000000", "00000000", "00000000", "00000000"]);
  assert(!zeroSeed.ok && zeroSeed.code === "invalid-seed-zero", "oracle accepted the all-zero Seed");
  const zeroState = oracleNext(oracleStateFromWords(["00000000", "00000000", "00000000", "00000000"]));
  assert(!zeroState.ok && zeroState.code === "invalid-state-zero", "oracle accepted the all-zero Generator State");
  const malformedReplay = oracleRestoreReplay({ schemaVersion: 1, sequenceProfile: SEQUENCE_PROFILE, seed: ["00000000"] });
  assert(!malformedReplay.ok && malformedReplay.code === "invalid-seed-shape", "Replay Token did not preserve Seed validation");
  const malformedSnapshot = oracleRestoreState({ schemaVersion: 1, sequenceProfile: SEQUENCE_PROFILE, state: ["0000000A", "00000000", "00000000", "00000001"] });
  assert(!malformedSnapshot.ok && malformedSnapshot.code === "invalid-state-word", "serialized state accepted a non-canonical word");
  const malformedSnapshotShape = oracleRestoreState({ schemaVersion: 1, sequenceProfile: SEQUENCE_PROFILE, state: ["00000001"] });
  assert(!malformedSnapshotShape.ok && malformedSnapshotShape.code === "invalid-state-shape", "serialized state did not reject a short state structurally");
};

const main = () => {
  const golden = readGolden();
  checkPinnedProfileAndInvalidPreflight();
  assert(golden.schemaVersion === PINNED_SCHEMA_VERSION, "golden schema version changed without a reviewed profile change");
  assert(golden.sequenceProfile === PINNED_SEQUENCE_PROFILE, "golden Sequence Profile changed without a reviewed profile change");
  words(golden.canonicalSeed, "canonicalSeed");
  words(golden.craftedRejectionState, "craftedRejectionState");
  checkTransitionCorpus(golden);
  checkSamplingCorpus(golden);
  checkReplayCorpus(golden);
  checkNegativeBoundaryCases();
  checkPrivateBoundary();
  console.log(`[issue-17] oracle/golden checks passed (${path.relative(process.cwd(), goldenFile)})`);
};

try {
  main();
} catch (error) {
  console.error(error.message);
  process.exitCode = 1;
}
